In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load your dataset
file_path = 'corporate.csv' 
data = pd.read_csv(file_path)
print(data)

   Company ID Corporate Income Tax Rate   Net Sales Operating Expenses  \
0     ABC-001                       20%  $5,000,000         $2,000,000
1     DEF-002                       18%  $7,000,000         $2,500,000
2     GHI-003                       22%  $8,000,000         $3,000,000
3     JKL-004                       17%  $6,000,000         $2,200,000
4     MNO-005                       21%  $9,000,000         $3,500,000
5     MNO-006                       14%  $8,000,000         $2,500,000
6     MNO-007                       23%  $5,000,000         $4,500,000
7     MNO-008                       21%  $6,000,000         $2,500,000
8     MNO-009                       16%  $5,000,000         $1,500,000
9     MNO-010                       15%  $3,000,000         $1,500,000
10    MNO-011                       21%  $4,000,000         $3,000,000
11    MNO-012                       20%  $9,000,000         $3,500,000
12    MNO-013                       19%  $8,000,000         $3,000,000
13    MNO-014                       17%  $7,000,000         $3,500,000
14    MNO-015                       16%  $2,000,000         $3,000,000
15    MNO-016                       22%  $5,000,000         $2,500,000
16    MNO-017                       15%  $7,000,000         $3,500,000
17    MNO-018                       24%  $6,000,000         $2,000,000
18    MNO-019                       10%  $4,000,000         $2,500,000
19    MNO-020                       16%  $3,000,000         $1,000,000
20    MNO-021                       17%  $6,000,000         $3,000,000
21    MNO-022                       19%  $3,000,000         $1,000,000
22    MNO-023                       14%  $7,000,000         $3,500,000
23    MNO-024                       16%  $3,000,000         $1,500,000
24    MNO-025                       19%  $7,000,000         $3,000,000
25    MNO-026                       21%  $8,000,000         $3,500,000
26    MNO-027                       13%  $5,000,000         $2,500,000
27    MNO-028                       12%  $9,000,000         $3,500,000
28    MNO-029                       20%  $5,000,000         $2,500,000
29    MNO-030                       18%  $2,000,000         $1,000,000
30    MNO-031                       15%  $4,000,000         $1,500,000
31    MNO-032                       12%  $5,000,000         $3,000,000
32    MNO-033                       16%  $6,000,000         $3,500,000
33    MNO-034                       14%  $7,000,000         $3,000,000
34    MNO-035                       13%  $9,000,000         $3,500,000
35    MNO-036                       11%  $8,000,000         $3,000,000
36    MNO-037                       20%  $4,000,000         $2,500,000
37    MNO-038                       19%  $2,000,000         $3,500,000
38    MNO-039                       17%  $6,000,000         $2,000,000
39    MNO-040                       13%  $5,000,000         $2,500,000
40    MNO-041                       16%  $9,000,000         $1,000,000
41    MNO-042                       21%  $7,000,000         $3,000,000
42    MNO-043                       16%  $6,000,000         $1,000,000
43    MNO-044                       15%  $8,000,000         $3,500,000
44    MNO-045                       14%  $2,000,000         $1,500,000
45    MNO-046                       13%  $4,000,000         $3,000,000
46    MNO-047                       12%  $2,000,000         $3,500,000
47    MNO-048                       19%  $3,000,000         $2,500,000
48    MNO-049                       20%  $5,000,000         $3,500,000
49    MNO-050                       15%  $7,000,000         $2,500,000

   Other Income Gross Profit Margin Operating Cash Flow Current Assets  \
0      $100,000                 40%            $500,000     $1,500,000
1      $150,000                 35%            $800,000     $2,000,000
2      $200,000                 38%          $1,000,000     $2,500,000
3      $120,000                 42%            $600,000     $1,800,000
4      $250,000                 36%            $450,000     $3,000,000
5      $350,000                 24%          $1,200,000     $3,500,000
6      $250,000                 33%            $300,000     $2,000,000
7      $150,000                 41%            $500,000     $2,000,000
8      $180,000                 23%            $700,000     $1,500,000
9      $140,000                 34%            $200,000     $1,000,000
10     $150,000                 23%            $600,000     $2,000,000
11     $350,000                 20%          $1,200,000     $3,000,000
12     $300,000                 15%          $1,200,000     $2,800,000
13     $250,000                 37%          $1,000,000     $3,000,000
14     $100,000                 38%            $200,000     $1,000,000
15     $250,000                 32%            $400,000     $2,000,000
16     $300,000                 36%          $1,200,000     $3,000,000
17     $250,000                 30%          $1,000,000     $2,500,000
18     $200,000                 40%            $700,000     $2,500,000
19     $150,000                 21%            $300,000     $1,500,000
20     $250,000                 32%          $1,000,000     $3,000,000
21     $100,000                 10%            $200,000     $1,000,000
22     $250,000                 20%          $1,200,000     $3,000,000
23     $100,000                 15%            $300,000     $1,000,000
24     $300,000                 31%          $1,000,000     $3,000,000
25     $350,000                 29%          $1,200,000     $3,200,000
26     $250,000                 32%            $900,000     $2,000,000
27     $450,000                 39%          $1,200,000     $3,500,000
28     $250,000                 29%            $800,000     $2,500,000
29     $100,000                 35%            $200,000     $1,000,000
30     $140,000                 23%            $600,000     $1,500,000
31     $150,000                 20%          $1,200,000     $2,000,000
32     $350,000                 15%          $1,200,000     $2,500,000
33     $300,000                 37%          $1,000,000     $1,800,000
34     $250,000                 38%            $200,000       $3000000
35     $100,000                 32%            $400,000     $3,500,000
36     $250,000                 36%          $1,200,000     $2,000,000
37     $300,000                 30%          $1,000,000     $2,000,000
38     $250,000                 40%            $700,000     $1,500,000
39     $200,000                 21%            $300,000     $1,000,000
40     $150,000                 32%          $1,000,000     $2,000,000
41     $250,000                 10%            $200,000     $3,000,000
42     $100,000                 20%          $1,200,000     $2,800,000
43     $250,000                 15%            $300,000     $3,000,000
44     $100,000                 31%          $1,000,000     $1,000,000
45     $300,000                 29%          $1,200,000     $2,000,000
46     $350,000                 32%            $900,000     $3,000,000
47     $250,000                 39%          $1,200,000     $2,500,000
48     $450,000                 29%            $800,000     $2,500,000
49     $250,000                 35%            $200,000     $1,500,000

   Current Liabilities Effective Tax Rate  Inventory Turnover  \
0             $800,000                18%                   8
1           $1,200,000                20%                  10
2           $1,500,000                22%                  12
3           $1,000,000                16%                   9
4           $1,800,000                25%                  11
5           $1,400,000                16%                   7
6             $800,000                15%                   8
7             $100,000                20%                   3
8             $600,000                28%                   6
9             $600,000                32%                   7
10            $800,000                31%                  11
11          $1,000,000                18%                  12
12          $1,000,000                17%                  11
13          $1,300,000                19%                  10
14            $700,000                15%                   3
15            $900,000                23%                   4
16            $700,000                12%                  14
17            $600,000                16%                   6
18          $1,800,000                17%                   9
19          $1,200,000                26%                  10
20            $500,000                23%                  12
21            $800,000                16%                  15
22          $1,000,000                24%                  10
23            $900,000                19%                   7
24            $500,000                23%                   8
25          $1,000,000                19%                   9
26            $500,000                18%                  11
27            $800,000                17%                   9
28          $1,200,000                19%                   8
29            $900,000                22%                   7
30          $1,000,000                18%                   7
31          $1,800,000                20%                   8
32          $1,400,000                22%                   3
33            $800,000                16%                   6
34            $100,000                25%                   7
35            $600,000                16%                  11
36            $600,000                15%                  12
37            $800,000                20%                  11
38          $1,000,000                28%                  10
39          $1,000,000                32%                   3
40          $1,300,000                31%                   4
41            $700,000                18%                  14
42            $900,000                17%                   6
43            $700,000                19%                   9
44            $600,000                15%                  10
45          $1,800,000                23%                  12
46          $1,200,000                12%                  15
47            $500,000                16%                  10
48            $800,000                17%                   7
49          $1,000,000                20%                   8

   Return on Assets (ROA)  Number of Employees Business Location  \
0                     12%                  150           Chennai
1                     15%                  200            Mumbai
2                     18%                  250           Kolkata
3                     14%                  180             Delhi
4                     20%                  300               Goa
5                     15%                  160            Kerala
6                     14%                  150           Gujarat
7                     17%                  210         Rajasthan
8                     20%                  220         Bengaluru
9                     11%                  100             Paris
10                    15%                  150           Chennai
11                    19%                  180            Mumbai
12                    18%                  150           Kolkata
13                    13%                  200             Delhi
14                    18%                  210               Goa
15                    10%                  120            Kerala
16                    12%                  140           Gujarat
17                    18%                  230         Rajasthan
18                    17%                  180         Bengaluru
19                    14%                  140             Paris
20                    11%                  100           Chennai
21                    18%                  210            Mumbai
22                    12%                  190           Kolkata
23                    18%                  170             Delhi
24                    10%                  160               Goa
25                    19%                  140            Kerala
26                    13%                  130           Gujarat
27                    10%                  120         Rajasthan
28                    20%                  100         Bengaluru
29                    19%                  150             Paris
30                    13%                  160           Chennai
31                    18%                  150            Mumbai
32                    10%                  210           Kolkata
33                    12%                  220             Delhi
34                    18%                  100               Goa
35                    17%                  150            Kerala
36                    14%                  180           Gujarat
37                    11%                  150         Rajasthan
38                    18%                  200         Bengaluru
39                    12%                  210             Paris
40                    18%                  120           Chennai
41                    10%                  140            Mumbai
42                    19%                  230           Kolkata
43                    13%                  180             Delhi
44                    10%                  140               Goa
45                    20%                  100            Kerala
46                    19%                  210           Gujarat
47                    12%                  190         Rajasthan
48                    15%                  170         Bengaluru
49                    16%                  160             Paris

    Industry Type Changes in Key Personnel
0   Manufacturing                      Yes
1      Technology                       No
2          Retail                      Yes
3        Services                       No
4         Finance                      Yes
5     Development                       No
6   Manufacturing                       No
7      Technology                      Yes
8          Retail                      Yes
9        Services                      Yes
10        Finance                      Yes
11    Development                       No
12  Manufacturing                       No
13     Technology                      Yes
14         Retail                       No
15       Services                      Yes
16        Finance                       No
17    Development                       No
18  Manufacturing                       No
19     Technology                      Yes
20         Retail                      Yes
21       Services                       No
22        Finance                       No
23    Development                       No
24  Manufacturing                      Yes
25     Technology                       No
26         Retail                       No
27       Services                       No
28        Finance                       No
29    Development                      Yes
30  Manufacturing                       No
31     Technology                      Yes
32         Retail                      Yes
33       Services                       No
34        Finance                      Yes
35    Development                       No
36  Manufacturing                       No
37     Technology                      Yes
38         Retail                      Yes
39       Services                      Yes
40  Manufacturing                      Yes
41     Technology                       No
42         Retail                       No
43       Services                       No
44        Finance                       No
45    Development                      Yes
46  Manufacturing                       No
47     Technology                       No
48         Retail                       No
49       Services                      Yes

In [3]:
# Convert columns with percentage signs to numeric after removing the percentage sign
percentage_columns = ['Corporate Income Tax Rate', 'Effective Tax Rate', 'Gross Profit Margin', 'Return on Assets (ROA)']
for col in percentage_columns:
    data[col] = data[col].str.replace('%', '').astype(float)

In [4]:
# Convert columns with currency signs to numeric after removing the currency sign and commas
currency_columns = ['Net Sales', 'Operating Expenses', 'Other Income', 'Operating Cash Flow', 'Current Assets', 'Current Liabilities']
for col in currency_columns:
    data[col] = data[col].replace({'\$': '', ',': ''}, regex=True).astype(float)

In [5]:
# Remove non-numeric columns or columns with non-essential information
data = data.drop(['Company ID', 'Business Location', 'Industry Type'], axis=1)
label_encoder = LabelEncoder()
data['Changes in Key Personnel'] = label_encoder.fit_transform(data['Changes in Key Personnel'])

In [6]:
print(data)
print(data.isnull().sum())

    Corporate Income Tax Rate  Net Sales  Operating Expenses  Other Income  \
0                        20.0  5000000.0           2000000.0      100000.0
1                        18.0  7000000.0           2500000.0      150000.0
2                        22.0  8000000.0           3000000.0      200000.0
3                        17.0  6000000.0           2200000.0      120000.0
4                        21.0  9000000.0           3500000.0      250000.0
5                        14.0  8000000.0           2500000.0      350000.0
6                        23.0  5000000.0           4500000.0      250000.0
7                        21.0  6000000.0           2500000.0      150000.0
8                        16.0  5000000.0           1500000.0      180000.0
9                        15.0  3000000.0           1500000.0      140000.0
10                       21.0  4000000.0           3000000.0      150000.0
11                       20.0  9000000.0           3500000.0      350000.0
12                       19.0  8000000.0           3000000.0      300000.0
13                       17.0  7000000.0           3500000.0      250000.0
14                       16.0  2000000.0           3000000.0      100000.0
15                       22.0  5000000.0           2500000.0      250000.0
16                       15.0  7000000.0           3500000.0      300000.0
17                       24.0  6000000.0           2000000.0      250000.0
18                       10.0  4000000.0           2500000.0      200000.0
19                       16.0  3000000.0           1000000.0      150000.0
20                       17.0  6000000.0           3000000.0      250000.0
21                       19.0  3000000.0           1000000.0      100000.0
22                       14.0  7000000.0           3500000.0      250000.0
23                       16.0  3000000.0           1500000.0      100000.0
24                       19.0  7000000.0           3000000.0      300000.0
25                       21.0  8000000.0           3500000.0      350000.0
26                       13.0  5000000.0           2500000.0      250000.0
27                       12.0  9000000.0           3500000.0      450000.0
28                       20.0  5000000.0           2500000.0      250000.0
29                       18.0  2000000.0           1000000.0      100000.0
30                       15.0  4000000.0           1500000.0      140000.0
31                       12.0  5000000.0           3000000.0      150000.0
32                       16.0  6000000.0           3500000.0      350000.0
33                       14.0  7000000.0           3000000.0      300000.0
34                       13.0  9000000.0           3500000.0      250000.0
35                       11.0  8000000.0           3000000.0      100000.0
36                       20.0  4000000.0           2500000.0      250000.0
37                       19.0  2000000.0           3500000.0      300000.0
38                       17.0  6000000.0           2000000.0      250000.0
39                       13.0  5000000.0           2500000.0      200000.0
40                       16.0  9000000.0           1000000.0      150000.0
41                       21.0  7000000.0           3000000.0      250000.0
42                       16.0  6000000.0           1000000.0      100000.0
43                       15.0  8000000.0           3500000.0      250000.0
44                       14.0  2000000.0           1500000.0      100000.0
45                       13.0  4000000.0           3000000.0      300000.0
46                       12.0  2000000.0           3500000.0      350000.0
47                       19.0  3000000.0           2500000.0      250000.0
48                       20.0  5000000.0           3500000.0      450000.0
49                       15.0  7000000.0           2500000.0      250000.0

    Gross Profit Margin  Operating Cash Flow  Current Assets  \
0                  40.0             500000.0       1500000.0
1                  35.0             800000.0       2000000.0
2                  38.0            1000000.0       2500000.0
3                  42.0             600000.0       1800000.0
4                  36.0             450000.0       3000000.0
5                  24.0            1200000.0       3500000.0
6                  33.0             300000.0       2000000.0
7                  41.0             500000.0       2000000.0
8                  23.0             700000.0       1500000.0
9                  34.0             200000.0       1000000.0
10                 23.0             600000.0       2000000.0
11                 20.0            1200000.0       3000000.0
12                 15.0            1200000.0       2800000.0
13                 37.0            1000000.0       3000000.0
14                 38.0             200000.0       1000000.0
15                 32.0             400000.0       2000000.0
16                 36.0            1200000.0       3000000.0
17                 30.0            1000000.0       2500000.0
18                 40.0             700000.0       2500000.0
19                 21.0             300000.0       1500000.0
20                 32.0            1000000.0       3000000.0
21                 10.0             200000.0       1000000.0
22                 20.0            1200000.0       3000000.0
23                 15.0             300000.0       1000000.0
24                 31.0            1000000.0       3000000.0
25                 29.0            1200000.0       3200000.0
26                 32.0             900000.0       2000000.0
27                 39.0            1200000.0       3500000.0
28                 29.0             800000.0       2500000.0
29                 35.0             200000.0       1000000.0
30                 23.0             600000.0       1500000.0
31                 20.0            1200000.0       2000000.0
32                 15.0            1200000.0       2500000.0
33                 37.0            1000000.0       1800000.0
34                 38.0             200000.0       3000000.0
35                 32.0             400000.0       3500000.0
36                 36.0            1200000.0       2000000.0
37                 30.0            1000000.0       2000000.0
38                 40.0             700000.0       1500000.0
39                 21.0             300000.0       1000000.0
40                 32.0            1000000.0       2000000.0
41                 10.0             200000.0       3000000.0
42                 20.0            1200000.0       2800000.0
43                 15.0             300000.0       3000000.0
44                 31.0            1000000.0       1000000.0
45                 29.0            1200000.0       2000000.0
46                 32.0             900000.0       3000000.0
47                 39.0            1200000.0       2500000.0
48                 29.0             800000.0       2500000.0
49                 35.0             200000.0       1500000.0

    Current Liabilities  Effective Tax Rate  Inventory Turnover  \
0              800000.0                18.0                   8
1             1200000.0                20.0                  10
2             1500000.0                22.0                  12
3             1000000.0                16.0                   9
4             1800000.0                25.0                  11
5             1400000.0                16.0                   7
6              800000.0                15.0                   8
7              100000.0                20.0                   3
8              600000.0                28.0                   6
9              600000.0                32.0                   7
10             800000.0                31.0                  11
11            1000000.0                18.0                  12
12            1000000.0                17.0                  11
13            1300000.0                19.0                  10
14             700000.0                15.0                   3
15             900000.0                23.0                   4
16             700000.0                12.0                  14
17             600000.0                16.0                   6
18            1800000.0                17.0                   9
19            1200000.0                26.0                  10
20             500000.0                23.0                  12
21             800000.0                16.0                  15
22            1000000.0                24.0                  10
23             900000.0                19.0                   7
24             500000.0                23.0                   8
25            1000000.0                19.0                   9
26             500000.0                18.0                  11
27             800000.0                17.0                   9
28            1200000.0                19.0                   8
29             900000.0                22.0                   7
30            1000000.0                18.0                   7
31            1800000.0                20.0                   8
32            1400000.0                22.0                   3
33             800000.0                16.0                   6
34             100000.0                25.0                   7
35             600000.0                16.0                  11
36             600000.0                15.0                  12
37             800000.0                20.0                  11
38            1000000.0                28.0                  10
39            1000000.0                32.0                   3
40            1300000.0                31.0                   4
41             700000.0                18.0                  14
42             900000.0                17.0                   6
43             700000.0                19.0                   9
44             600000.0                15.0                  10
45            1800000.0                23.0                  12
46            1200000.0                12.0                  15
47             500000.0                16.0                  10
48             800000.0                17.0                   7
49            1000000.0                20.0                   8

    Return on Assets (ROA)  Number of Employees  Changes in Key Personnel
0                     12.0                  150                         1
1                     15.0                  200                         0
2                     18.0                  250                         1
3                     14.0                  180                         0
4                     20.0                  300                         1
5                     15.0                  160                         0
6                     14.0                  150                         0
7                     17.0                  210                         1
8                     20.0                  220                         1
9                     11.0                  100                         1
10                    15.0                  150                         1
11                    19.0                  180                         0
12                    18.0                  150                         0
13                    13.0                  200                         1
14                    18.0                  210                         0
15                    10.0                  120                         1
16                    12.0                  140                         0
17                    18.0                  230                         0
18                    17.0                  180                         0
19                    14.0                  140                         1
20                    11.0                  100                         1
21                    18.0                  210                         0
22                    12.0                  190                         0
23                    18.0                  170                         0
24                    10.0                  160                         1
25                    19.0                  140                         0
26                    13.0                  130                         0
27                    10.0                  120                         0
28                    20.0                  100                         0
29                    19.0                  150                         1
30                    13.0                  160                         0
31                    18.0                  150                         1
32                    10.0                  210                         1
33                    12.0                  220                         0
34                    18.0                  100                         1
35                    17.0                  150                         0
36                    14.0                  180                         0
37                    11.0                  150                         1
38                    18.0                  200                         1
39                    12.0                  210                         1
40                    18.0                  120                         1
41                    10.0                  140                         0
42                    19.0                  230                         0
43                    13.0                  180                         0
44                    10.0                  140                         0
45                    20.0                  100                         1
46                    19.0                  210                         0
47                    12.0                  190                         0
48                    15.0                  170                         0
49                    16.0                  160                         1
Corporate Income Tax Rate    0
Net Sales                    0
Operating Expenses           0
Other Income                 0
Gross Profit Margin          0
Operating Cash Flow          0
Current Assets               0
Current Liabilities          0
Effective Tax Rate           0
Inventory Turnover           0
Return on Assets (ROA)       0
Number of Employees          0
Changes in Key Personnel     0
dtype: int64

In [7]:
datas = data.fillna(data.mean())
print(datas)

    Corporate Income Tax Rate  Net Sales  Operating Expenses  Other Income  \
0                        20.0  5000000.0           2000000.0      100000.0
1                        18.0  7000000.0           2500000.0      150000.0
2                        22.0  8000000.0           3000000.0      200000.0
3                        17.0  6000000.0           2200000.0      120000.0
4                        21.0  9000000.0           3500000.0      250000.0
5                        14.0  8000000.0           2500000.0      350000.0
6                        23.0  5000000.0           4500000.0      250000.0
7                        21.0  6000000.0           2500000.0      150000.0
8                        16.0  5000000.0           1500000.0      180000.0
9                        15.0  3000000.0           1500000.0      140000.0
10                       21.0  4000000.0           3000000.0      150000.0
11                       20.0  9000000.0           3500000.0      350000.0
12                       19.0  8000000.0           3000000.0      300000.0
13                       17.0  7000000.0           3500000.0      250000.0
14                       16.0  2000000.0           3000000.0      100000.0
15                       22.0  5000000.0           2500000.0      250000.0
16                       15.0  7000000.0           3500000.0      300000.0
17                       24.0  6000000.0           2000000.0      250000.0
18                       10.0  4000000.0           2500000.0      200000.0
19                       16.0  3000000.0           1000000.0      150000.0
20                       17.0  6000000.0           3000000.0      250000.0
21                       19.0  3000000.0           1000000.0      100000.0
22                       14.0  7000000.0           3500000.0      250000.0
23                       16.0  3000000.0           1500000.0      100000.0
24                       19.0  7000000.0           3000000.0      300000.0
25                       21.0  8000000.0           3500000.0      350000.0
26                       13.0  5000000.0           2500000.0      250000.0
27                       12.0  9000000.0           3500000.0      450000.0
28                       20.0  5000000.0           2500000.0      250000.0
29                       18.0  2000000.0           1000000.0      100000.0
30                       15.0  4000000.0           1500000.0      140000.0
31                       12.0  5000000.0           3000000.0      150000.0
32                       16.0  6000000.0           3500000.0      350000.0
33                       14.0  7000000.0           3000000.0      300000.0
34                       13.0  9000000.0           3500000.0      250000.0
35                       11.0  8000000.0           3000000.0      100000.0
36                       20.0  4000000.0           2500000.0      250000.0
37                       19.0  2000000.0           3500000.0      300000.0
38                       17.0  6000000.0           2000000.0      250000.0
39                       13.0  5000000.0           2500000.0      200000.0
40                       16.0  9000000.0           1000000.0      150000.0
41                       21.0  7000000.0           3000000.0      250000.0
42                       16.0  6000000.0           1000000.0      100000.0
43                       15.0  8000000.0           3500000.0      250000.0
44                       14.0  2000000.0           1500000.0      100000.0
45                       13.0  4000000.0           3000000.0      300000.0
46                       12.0  2000000.0           3500000.0      350000.0
47                       19.0  3000000.0           2500000.0      250000.0
48                       20.0  5000000.0           3500000.0      450000.0
49                       15.0  7000000.0           2500000.0      250000.0

    Gross Profit Margin  Operating Cash Flow  Current Assets  \
0                  40.0             500000.0       1500000.0
1                  35.0             800000.0       2000000.0
2                  38.0            1000000.0       2500000.0
3                  42.0             600000.0       1800000.0
4                  36.0             450000.0       3000000.0
5                  24.0            1200000.0       3500000.0
6                  33.0             300000.0       2000000.0
7                  41.0             500000.0       2000000.0
8                  23.0             700000.0       1500000.0
9                  34.0             200000.0       1000000.0
10                 23.0             600000.0       2000000.0
11                 20.0            1200000.0       3000000.0
12                 15.0            1200000.0       2800000.0
13                 37.0            1000000.0       3000000.0
14                 38.0             200000.0       1000000.0
15                 32.0             400000.0       2000000.0
16                 36.0            1200000.0       3000000.0
17                 30.0            1000000.0       2500000.0
18                 40.0             700000.0       2500000.0
19                 21.0             300000.0       1500000.0
20                 32.0            1000000.0       3000000.0
21                 10.0             200000.0       1000000.0
22                 20.0            1200000.0       3000000.0
23                 15.0             300000.0       1000000.0
24                 31.0            1000000.0       3000000.0
25                 29.0            1200000.0       3200000.0
26                 32.0             900000.0       2000000.0
27                 39.0            1200000.0       3500000.0
28                 29.0             800000.0       2500000.0
29                 35.0             200000.0       1000000.0
30                 23.0             600000.0       1500000.0
31                 20.0            1200000.0       2000000.0
32                 15.0            1200000.0       2500000.0
33                 37.0            1000000.0       1800000.0
34                 38.0             200000.0       3000000.0
35                 32.0             400000.0       3500000.0
36                 36.0            1200000.0       2000000.0
37                 30.0            1000000.0       2000000.0
38                 40.0             700000.0       1500000.0
39                 21.0             300000.0       1000000.0
40                 32.0            1000000.0       2000000.0
41                 10.0             200000.0       3000000.0
42                 20.0            1200000.0       2800000.0
43                 15.0             300000.0       3000000.0
44                 31.0            1000000.0       1000000.0
45                 29.0            1200000.0       2000000.0
46                 32.0             900000.0       3000000.0
47                 39.0            1200000.0       2500000.0
48                 29.0             800000.0       2500000.0
49                 35.0             200000.0       1500000.0

    Current Liabilities  Effective Tax Rate  Inventory Turnover  \
0              800000.0                18.0                   8
1             1200000.0                20.0                  10
2             1500000.0                22.0                  12
3             1000000.0                16.0                   9
4             1800000.0                25.0                  11
5             1400000.0                16.0                   7
6              800000.0                15.0                   8
7              100000.0                20.0                   3
8              600000.0                28.0                   6
9              600000.0                32.0                   7
10             800000.0                31.0                  11
11            1000000.0                18.0                  12
12            1000000.0                17.0                  11
13            1300000.0                19.0                  10
14             700000.0                15.0                   3
15             900000.0                23.0                   4
16             700000.0                12.0                  14
17             600000.0                16.0                   6
18            1800000.0                17.0                   9
19            1200000.0                26.0                  10
20             500000.0                23.0                  12
21             800000.0                16.0                  15
22            1000000.0                24.0                  10
23             900000.0                19.0                   7
24             500000.0                23.0                   8
25            1000000.0                19.0                   9
26             500000.0                18.0                  11
27             800000.0                17.0                   9
28            1200000.0                19.0                   8
29             900000.0                22.0                   7
30            1000000.0                18.0                   7
31            1800000.0                20.0                   8
32            1400000.0                22.0                   3
33             800000.0                16.0                   6
34             100000.0                25.0                   7
35             600000.0                16.0                  11
36             600000.0                15.0                  12
37             800000.0                20.0                  11
38            1000000.0                28.0                  10
39            1000000.0                32.0                   3
40            1300000.0                31.0                   4
41             700000.0                18.0                  14
42             900000.0                17.0                   6
43             700000.0                19.0                   9
44             600000.0                15.0                  10
45            1800000.0                23.0                  12
46            1200000.0                12.0                  15
47             500000.0                16.0                  10
48             800000.0                17.0                   7
49            1000000.0                20.0                   8

    Return on Assets (ROA)  Number of Employees  Changes in Key Personnel
0                     12.0                  150                         1
1                     15.0                  200                         0
2                     18.0                  250                         1
3                     14.0                  180                         0
4                     20.0                  300                         1
5                     15.0                  160                         0
6                     14.0                  150                         0
7                     17.0                  210                         1
8                     20.0                  220                         1
9                     11.0                  100                         1
10                    15.0                  150                         1
11                    19.0                  180                         0
12                    18.0                  150                         0
13                    13.0                  200                         1
14                    18.0                  210                         0
15                    10.0                  120                         1
16                    12.0                  140                         0
17                    18.0                  230                         0
18                    17.0                  180                         0
19                    14.0                  140                         1
20                    11.0                  100                         1
21                    18.0                  210                         0
22                    12.0                  190                         0
23                    18.0                  170                         0
24                    10.0                  160                         1
25                    19.0                  140                         0
26                    13.0                  130                         0
27                    10.0                  120                         0
28                    20.0                  100                         0
29                    19.0                  150                         1
30                    13.0                  160                         0
31                    18.0                  150                         1
32                    10.0                  210                         1
33                    12.0                  220                         0
34                    18.0                  100                         1
35                    17.0                  150                         0
36                    14.0                  180                         0
37                    11.0                  150                         1
38                    18.0                  200                         1
39                    12.0                  210                         1
40                    18.0                  120                         1
41                    10.0                  140                         0
42                    19.0                  230                         0
43                    13.0                  180                         0
44                    10.0                  140                         0
45                    20.0                  100                         1
46                    19.0                  210                         0
47                    12.0                  190                         0
48                    15.0                  170                         0
49                    16.0                  160                         1

In [8]:
# Separate features and target variable
X = datas.drop('Changes in Key Personnel', axis=1)
y = datas['Changes in Key Personnel']

In [9]:
# Feature scaling for better model performance
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [10]:
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[ 0.61075185  1.1249969   0.4426827   0.80946058 -1.68634964  1.1916484
   0.761641    0.18043874 -0.63233082  0.72531852  0.87082768 -0.45062974]
 [ 1.20371482  1.59768467  1.03135651  0.25805691  0.75932318 -0.82581503
   1.02794905  2.24259579  0.98903026  0.72531852  1.47139849  3.06991509]
 [ 0.61075185 -1.71112973  1.03135651  0.80946058  0.06055952  0.65365815
  -0.30359117 -0.33510052 -0.02432042  0.72531852 -1.23117017 -0.45062974]
 [-0.27869259 -0.29306642 -1.32333871 -0.51390822 -0.75466475 -0.15332722
  -0.96936128 -0.85063978  1.59704067 -0.92313266  1.47139849  1.19229118]
 [ 0.01778889  0.17962135 -0.49919539 -1.17559261  1.45808684 -0.42232234
  -0.56989921  0.18043874 -0.83500096  0.06593805 -0.33031395  0.25347923]
 [ 1.79667778 -0.29306642  2.20870412  0.25805691  0.40994135 -1.22930772
  -0.30359117 -0.33510052 -1.0376711  -0.26375219 -0.33031395 -0.45062974]
 [ 1.20371482  0.65230913  0.4426827   0.25805691 -2.26865269 -1.49830284
   1.02794905 -0.59287015 -0.42966069  1.71438923 -1.53145557 -0.68533273]
 [-1.46461852 -1.71112973  1.03135651  1.36086424  0.29348074  0.38466303
   1.02794905  0.695978   -1.6456815   2.04407947  1.17111309  0.95758819]
 [ 0.61075185 -1.23844196 -0.1459911   0.25805691  1.10870501  1.1916484
   0.36217894 -1.10840941 -0.83500096  0.39562828 -0.93088476  0.48818222]
 [ 1.5001963  -0.29306642 -0.1459911   0.25805691  0.29348074 -0.96031259
  -0.30359117 -0.07733089  0.58368999 -1.58251314 -1.53145557 -1.1547387 ]
 [-0.57517408 -1.23844196 -1.32333871 -0.95503115  0.52640196 -1.49830284
  -1.63513139 -0.85063978  2.40772122 -0.59344243 -1.23117017 -1.62414468]
 [-0.57517408  0.65230913  1.03135651  0.80946058  0.75932318  1.1916484
   1.02794905 -0.59287015 -1.6456815   1.71438923 -0.93088476 -0.68533273]
 [ 0.61075185  0.65230913  0.4426827   0.80946058  0.17702013  0.65365815
   1.02794905 -1.10840941  0.58368999 -0.26375219 -1.53145557 -0.21592675]
 [-1.16813704  1.59768467  1.03135651  0.25805691  0.9922444  -1.49830284
   1.02794905 -2.13948794  0.98903026 -0.59344243  0.87082768 -1.62414468]
 [-1.46461852 -0.29306642  0.4426827  -0.84475041 -1.10404658  1.1916484
  -0.30359117  2.24259579 -0.02432042 -0.26375219  0.87082768 -0.45062974]
 [ 0.90723334 -0.29306642 -0.73466491 -1.39615408  1.22516562 -0.69131747
  -0.96936128 -0.33510052 -0.42966069 -0.26375219 -0.93088476 -0.45062974]
 [-0.87165556 -1.71112973 -1.32333871 -1.39615408  0.17702013  0.65365815
  -1.63513139 -0.85063978 -1.0376711   0.39562828 -1.53145557 -0.68533273]
 [-1.46461852  1.59768467  1.03135651  2.46367157  1.10870501  1.1916484
   1.69371916 -0.33510052 -0.63233082  0.06593805 -1.53145557 -1.1547387 ]
 [-0.87165556  0.65230913  0.4426827   0.80946058  0.87578379  0.65365815
  -0.56989921 -0.33510052 -0.83500096 -0.92313266 -0.93088476  1.19229118]
 [-0.87165556  1.1249969  -0.1459911   1.36086424 -0.63820414  1.1916484
   1.69371916  1.21151727 -0.83500096 -0.59344243 -0.03002854 -0.21592675]
 [ 0.31427037 -1.71112973 -1.91201252 -1.39615408  0.64286257 -1.49830284
  -1.63513139 -0.07733089  0.38101986 -0.59344243  1.17111309 -0.45062974]
 [ 0.90723334  1.59768467  1.03135651  1.36086424 -1.10404658  1.1916484
   1.02794905  0.18043874 -0.42966069  1.05500876  1.17111309  0.25347923]
 [ 0.90723334 -0.76575419 -0.1459911   0.25805691  0.75932318  1.1916484
  -0.30359117 -0.85063978 -1.0376711   1.05500876 -0.33031395  0.25347923]
 [ 0.31427037  0.65230913 -0.1459911  -0.84475041  0.64286257  0.1156679
  -0.30359117  0.695978   -0.02432042  0.39562828 -0.03002854  0.7228852 ]
 [ 0.61075185 -1.23844196 -1.91201252 -1.39615408 -2.26865269 -1.49830284
  -1.63513139 -0.33510052 -0.83500096  2.04407947  0.87082768  0.95758819]
 [ 1.5001963   1.1249969   0.4426827  -0.29334675  0.9922444   0.65365815
   0.36217894  1.4692869   0.38101986  1.05500876  0.87082768  1.89640014]
 [-0.57517408  1.1249969   1.03135651  0.25805691 -1.68634964 -1.22930772
   1.02794905 -0.59287015 -0.22699055  0.06593805 -0.63059935  0.25347923]
 [-1.7611      1.1249969   0.4426827  -1.39615408  0.29348074 -0.96031259
   1.69371916 -0.85063978 -0.83500096  0.72531852  0.57054227 -0.45062974]
 [-0.27869259 -1.23844196 -1.32333871 -1.39615408 -1.68634964 -1.22930772
  -1.63513139 -0.07733089 -0.22699055 -0.59344243  0.87082768  0.01877624]
 [-0.27869259  1.59768467 -1.91201252 -0.84475041  0.29348074  0.65365815
  -0.30359117  0.95374764  2.20505108 -1.58251314  0.87082768 -1.1547387 ]
 [ 1.20371482 -0.76575419  0.4426827  -0.84475041 -0.75466475 -0.42232234
  -0.30359117 -0.33510052  2.20505108  0.72531852 -0.03002854 -0.45062974]
 [-0.87165556  0.65230913  1.03135651  0.25805691 -1.10404658  1.1916484
   1.02794905  0.18043874  0.78636013  0.39562828 -0.93088476  0.48818222]
 [-2.05758149 -0.76575419 -0.1459911  -0.29334675  1.22516562 -0.15332722
   0.36217894  2.24259579 -0.63233082  0.06593805  0.57054227  0.25347923]
 [-0.57517408  0.65230913 -0.1459911   0.25805691  0.64286257 -1.49830284
  -0.96936128  0.18043874 -0.02432042 -0.26375219  0.27025687 -0.21592675]
 [ 0.01778889  0.17962135  0.4426827   0.25805691  0.29348074  0.65365815
   1.02794905 -1.10840941  0.58368999  1.05500876 -1.23117017 -1.62414468]
 [ 1.20371482  0.17962135 -0.1459911  -0.84475041  1.34162623 -0.69131747
  -0.30359117 -2.13948794 -0.02432042 -1.91220337  0.57054227  0.95758819]
 [-0.27869259  0.17962135 -1.91201252 -1.39615408 -1.10404658  1.1916484
   0.761641   -0.07733089 -0.63233082 -0.92313266  1.17111309  1.42699417]
 [-0.27869259 -1.71112973  0.4426827  -1.39615408  0.9922444  -1.49830284
  -1.63513139 -0.59287015 -1.0376711  -1.91220337  0.87082768  0.95758819]
 [ 0.90723334 -0.29306642 -0.1459911   0.25805691 -0.05590109  0.1156679
   0.36217894  0.695978   -0.22699055 -0.26375219  1.47139849 -1.62414468]
 [ 0.01778889  0.17962135 -0.73466491  0.25805691  1.22516562 -0.15332722
  -0.96936128  0.18043874  1.59704067  0.39562828  0.87082768  0.7228852 ]]
12    0
4     1
37    1
8     1
3     0
6     0
41    0
46    0
47    0
15    1
9     1
16    0
24    1
34    1
31    1
0     1
44    0
27    0
33    0
5     0
29    1
11    0
36    0
1     0
21    0
2     1
43    0
35    0
23    0
40    1
10    1
22    0
18    0
49    1
20    1
7     1
42    0
14    0
28    0
38    1
Name: Changes in Key Personnel, dtype: int32
[[ 0.01778889  0.65230913  1.03135651  0.25805691  0.87578379  0.65365815
   1.02794905  0.95374764 -0.22699055  0.39562828 -0.63059935  0.7228852 ]
 [-1.16813704 -0.29306642 -0.1459911  -0.29334675 -0.98758597 -1.22930772
  -1.63513139  0.18043874  2.40772122 -1.91220337 -0.93088476  0.95758819]
 [-0.57517408 -0.76575419 -1.32333871 -0.95503115 -0.75466475 -0.42232234
  -0.96936128  0.18043874 -0.42966069 -0.59344243 -0.63059935 -0.21592675]
 [-1.16813704 -0.76575419  0.4426827   0.80946058 -0.05590109  1.1916484
  -0.30359117  2.24259579  0.58368999  1.05500876  1.47139849 -1.62414468]
 [ 2.09315926  0.17962135 -0.73466491  0.25805691  0.06055952  0.65365815
   0.36217894 -0.85063978 -0.83500096 -0.92313266  0.87082768  1.42699417]
 [ 0.90723334 -0.29306642  1.03135651  2.46367157 -0.05590109  0.1156679
   0.36217894 -0.33510052 -0.63233082 -0.59344243 -0.03002854  0.01877624]
 [-1.16813704 -0.29306642 -0.1459911   0.25805691  0.29348074  0.38466303
  -0.30359117 -1.10840941 -0.42966069  0.72531852 -0.63059935 -0.92003571]
 [ 1.20371482  1.1249969   1.03135651  1.36086424 -0.05590109  1.1916484
   1.29425709  0.18043874 -0.22699055  0.06593805  1.17111309 -0.68533273]
 [-0.27869259  0.17962135  1.03135651  1.36086424 -1.68634964  1.1916484
   0.36217894  1.21151727  0.38101986 -1.91220337 -1.53145557  0.95758819]
 [-0.27869259 -1.23844196 -1.91201252 -0.84475041 -0.98758597 -1.22930772
  -0.96936128  0.695978    1.1917004   0.39562828 -0.33031395 -0.68533273]]
13    1
39    1
30    0
45    1
17    0
48    0
26    0
25    0
32    1
19    1
Name: Changes in Key Personnel, dtype: int32

In [11]:
print(datas.isnull().sum())

Corporate Income Tax Rate    0
Net Sales                    0
Operating Expenses           0
Other Income                 0
Gross Profit Margin          0
Operating Cash Flow          0
Current Assets               0
Current Liabilities          0
Effective Tax Rate           0
Inventory Turnover           0
Return on Assets (ROA)       0
Number of Employees          0
Changes in Key Personnel     0
dtype: int64

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize the Random Forest Classifier
clf = RandomForestClassifier(random_state=32)

# Fit the model on the training data
clf.fit(X_train,y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)


# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

In [13]:
# Generate and print the classification report and confusion matrix
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.71      1.00      0.83         5
           1       1.00      0.60      0.75         5

    accuracy                           0.80        10
   macro avg       0.86      0.80      0.79        10
weighted avg       0.86      0.80      0.79        10


Confusion Matrix:
[[5 0]
 [2 3]]

In [ ]:
# Initializing Random Forest and Gradient Boosting Classifiers
rf_clf = RandomForestClassifier(random_state=32)
gb_clf = GradientBoostingClassifier(random_state=32)

# Fitting the models
rf_clf.fit(X_train, y_train)
gb_clf.fit(X_train, y_train)

In [15]:
rf_y_pred = rf_clf.predict(X_test)
gb_y_pred = gb_clf.predict(X_test)

In [16]:
# Evaluating Gradient Boosting Classifier
gb_accuracy = accuracy_score(y_test, gb_y_pred)
print(f"\nGradient Boosting Classifier Accuracy: {gb_accuracy:.2f}")
print("\nGradient Boosting Classifier Report:")
print(classification_report(y_test, gb_y_pred))
print("\nGradient Boosting Classifier Confusion Matrix:")
print(confusion_matrix(y_test, gb_y_pred))

Gradient Boosting Classifier Accuracy: 0.70

Gradient Boosting Classifier Report:
              precision    recall  f1-score   support

           0       0.62      1.00      0.77         5
           1       1.00      0.40      0.57         5

    accuracy                           0.70        10
   macro avg       0.81      0.70      0.67        10
weighted avg       0.81      0.70      0.67        10


Gradient Boosting Classifier Confusion Matrix:
[[5 0]
 [3 2]]

In [ ]:

# Get input from the user for prediction
user_input = {}

print("Enter the required details for prediction:")
for col in X.columns:
    user_input[col] = input(f"Enter value for '{col}': ")

# Create a DataFrame from the user input
user_df = pd.DataFrame([user_input])

# Convert user input to numeric format
for col in user_df.columns:
    if user_df[col].dtype == object:  # Check if the column type is object (string)
        if user_df[col].str.contains('%').any():
            user_df[col] = user_df[col].str.replace('%', '').astype(float)
        elif user_df[col].str.contains('$').any():
            user_df[col] = user_df[col].replace({'\$': '', ',': ''}, regex=True).astype(float)
        else:
            user_df[col] = user_df[col].astype(float)

# Scale the user input data
user_scaled = scaler.transform(user_df)

# Predict with the Random Forest Classifier
user_prediction_rf = clf.predict(user_scaled)

# Predict with the Gradient Boosting Classifier
user_prediction_gb = gb_clf.predict(user_scaled)

# Display the user input and predictions
print("\nUser Input:")
print(user_df)

print("\nPrediction Results:")
print(f"Random Forest Classifier Prediction: {'Yes' if user_prediction_rf[0] == 1 else 'No'}")
print(f"Gradient Boosting Classifier Prediction: {'Yes' if user_prediction_gb[0] == 1 else 'No'}")

Enter the required details for prediction: